version: "3.9"
services:
  my-task-board:
    image: postgres
    restart: always
    container_name: my-task-board
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
